apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootworker
  MYSQL_DATABASE: mrbs
  MYSQL_USER: worker
  MYSQL_PASSWORD: worker
  DATABASE_URL: mysql://worker:worker@mysql:3306/mrbs