apiVersion: v1
kind: Service
metadata:
  name: workspace-booking-app
spec:
  selector:
    app: workspace-booking-app
  ports:
    - name: http
      port: 5150
      targetPort: 5150
      nodePort: 30150
  type: NodePort