apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-booking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workspace-booking-app
  template:
    metadata:
      labels:
        app: workspace-booking-app
    spec:
      containers:
        - name: app
          image: ghcr.io/martin1088/workspace-booking-system:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5150
          envFrom:
            - secretRef:
                name: oauth-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /
              port: 5150
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5150
            initialDelaySeconds: 15
            periodSeconds: 20
      